"""add BlacklistedToken model

Revision ID: 97f449048b52
Revises: 5789387e80dd
Create Date: 2020-01-14 08:32:07.797763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97f449048b52"
down_revision = "5789387e80dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
